spring:
  profiles:
    active: development
    
---
spring:
  profile: development
configuration:  
  projectName: configclient
server:  
  port: 8001
message:  
  greeting: development profile configuration client
