spring:
  profiles:
    active: stage
    
---
spring:
  profile: development
configuration:  
  projectName: configclient
server:  
  port: 8001
message:  
  greeting: development profile configuration client

---
spring:
  profile: stage
configuration:  
  projectName: configclient
server:  
  port: 8002
message:  
  greeting: stage profile configuration client
